### PR TITLE
Feature -  support for HTTP PUT request

### PR DESCRIPTION
**Pull request by Z14tk0**
Midpoint supports **HTTP PUT** requests but from my code analysis of the client lib i didnt see a way to make PUT requests.

Folowing code modification enables PUT requests. Idea is to be able to do something like this:

midpointClient.users().replace(user.getOid(), user).post()

Main goal was to do minimal changes to source code and reuse existing .post() logic to support this. Hope you are ok with this solution.

Best regards, thank you
Z14tk0

### CODE REVIEW

**Comment by matusmacik** [comment]
Hello thank you for this contribution, the feature is certainly welcome. 

There are a couple of changes I would like to suggest. 
As this feature should use the PUT HTTP operation, the POST verb should not be used, and rather a new verb Interface “put” implemented with a method “put” and “aput” (as in the “post” interface).

“ObjectReplaceService<O extends ObjectType> ” could extend this “put” interface rather than post.

The “com.evolveum.midpoint.client.api.ObjectService” interface could contain the method “ObjectReplaceService<O> replace(String oid, O object)” rather than the  “com.evolveum.midpoint.client.api.ObjectCollectionService” interface.

The implementation of the “replace” method could reside in “com.evolveum.midpoint.client.impl.restjaxb.RestJaxbObjectService”.
 Also an implementation in “com.evolveum.midpoint.client.impl.prism.RestPrismObjectService” would be needed but in this case, an UnsupportedOperationException() could be returned the same as with the “modify” method.

The invocation could then look like this: 
service.users().oid(USER_JACK_OID).replace(user).put()

**Comment by Z14tk0** [comment]
> Hello thank you for this contribution, the feature is certainly welcome.
> 
> There are a couple of changes I would like to suggest. As this feature should use the PUT HTTP operation, the POST verb should not be used, and rather a new verb Interface “put” implemented with a method “put” and “aput” (as in the “post” interface).
> 
> “ObjectReplaceService ” could extend this “put” interface rather than post.
> 
> The “com.evolveum.midpoint.client.api.ObjectService” interface could contain the method “ObjectReplaceService replace(String oid, O object)” rather than the “com.evolveum.midpoint.client.api.ObjectCollectionService” interface.
> 
> The implementation of the “replace” method could reside in “com.evolveum.midpoint.client.impl.restjaxb.RestJaxbObjectService”. Also an implementation in “com.evolveum.midpoint.client.impl.prism.RestPrismObjectService” would be needed but in this case, an UnsupportedOperationException() could be returned the same as with the “modify” method.
> 
> The invocation could then look like this: service.users().oid(USER_JACK_OID).replace(user).put()

Thank you for you respected comments as soon as i find time in the next few days i will correct this folowing your guidelines. I understand that i done this a bit wierd

**Comment by Z14tk0** [comment]
> Hello thank you for this contribution, the feature is certainly welcome.
> 
> There are a couple of changes I would like to suggest. As this feature should use the PUT HTTP operation, the POST verb should not be used, and rather a new verb Interface “put” implemented with a method “put” and “aput” (as in the “post” interface).
> 
> “ObjectReplaceService ” could extend this “put” interface rather than post.
> 
> The “com.evolveum.midpoint.client.api.ObjectService” interface could contain the method “ObjectReplaceService replace(String oid, O object)” rather than the “com.evolveum.midpoint.client.api.ObjectCollectionService” interface.
> 
> The implementation of the “replace” method could reside in “com.evolveum.midpoint.client.impl.restjaxb.RestJaxbObjectService”. Also an implementation in “com.evolveum.midpoint.client.impl.prism.RestPrismObjectService” would be needed but in this case, an UnsupportedOperationException() could be returned the same as with the “modify” method.
> 
> The invocation could then look like this: service.users().oid(USER_JACK_OID).replace(user).put()

Thank you Matus for your respected comments and guidelines. I know I done this a bit weird at first 🙈 and I agree with you that this had to be done like you said from the start. I corrected it now following your guidelines. Let me know if its ok now.

Best regards,
Z14tk0

**Comment by matusmacik** [comment]
Thank you for the changes, the implementation was good, the main issue was the final syntax, otherwise great :). Thank you for your contribution.

**Pull request merged**
